spring:
  datasource:
    username: codelex
    password: krists
    url: jdbc:postgresql://localhost:5432/micro-lending
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/liquibase/updates.xml
    enabled: false

